import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Contact US</h1>
      <p className="sub-title" >Any question or remarks? Just write us a message!</p>

      <div id="contact-container">
        <div className="contact-info">
          <h4>
            Contact Information
          </h4>
          <p>Fill up the form and our team will get back</p>
          <div className="icon-text">
            <i class="fa fa-phone" aria-hidden="true"></i>
            <span>123456789</span>
          </div>
          <div className="icon-text">
            <i class="fa fa-envelope" aria-hidden="true"></i>
            <span>addyourmail.gmail.com</span>
          </div>
          <div className="icon-text">
            <i class="fa fa-map-marker" aria-hidden="true"></i>
            <span>Aashraya main office address</span>
          </div>
          <div className="social-media">
            <a href="#" className="icon-circle">
              <i class="fab fa-facebook-f"></i>
            </a>
            <a href="#" className="icon-circle">
              <i class="fab fa-twitter"></i>
            </a>
            <a href="#" className="icon-circle">
              <i class="fab fa-instagram"></i>

            </a>
            <a href="#" className="icon-circle">
              <i class="fab fa-youtube"></i>
            </a>
          </div>
        </div>
        <form>
          <div className="col">
            <div className="form-group">
              <label>First Name</label>
              <input type="text" />
            </div>
            <div className="form-group">
              <label>Last Name</label>
              <input type="text" />
            </div>
          </div>
          <div className="col">
            <div className="form-group">
              <label>E-Mail</label>
              <input type="email" />
            </div>
            <div className="form-group">
              <label>Phone</label>
              <input type="tel" />
            </div>
          </div>
          <div className="col">
            <div className="form-group">
              <label>Write Your message </label>

              <textarea></textarea>

            </div>


          </div>
          <div className="form-group right">
            <button className="Primary">Send message</button>

          </div>
        </form>
      </div >
    </>
  )
}
